#!/bin/zsh

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

alias fuzzy-pip-install='
    curl -s https://pypi.org/simple/ | 
    grep -o "simple\/.*\/" |
    awk -F'/' "{print \$2}" |
    fzf -m --header "Use TAB to select/unselect, ESC to exit" |
    xargs -I {} pip install {}'

alias gpup='git push -u origin $(git branch --show-current)'